### ISSUE TITLE
ViewPager sometimes displays 'empty' pages

### ISSUE THREAD

**Issue by AeroEchelon** [antonyt/InfiniteViewPager#23]
I've noticed that when you initialize a fragment with this ViewPager, navigate away then navigate 'Back'; an empty page is shown. After navigating back to this fragment, you can continue to swipe on the pager, then after X amount of items the view pager it against populated with more items.

Initializing a fragment with this ViewPager seems to work fine; however, coming back to a fragment that had already been created creates some blank pages.

**Comment by tmmiller1982** [comment]
Any update on this?  I'm seeing this same thing.

**Comment by AeroEchelon** [comment]
@tmmiller1982, I fixed this issue by constructing the corresponding adapter, `FragmentStatePagerAdapter` with `Fragment#getChildFragmentManager()`. If you have a fragment within a fragment you need to construct this new fragment with a _child fragment manager_ so it can handle the Back navigation appropriately.

It took me a while to figure this one out ... it should be documented somewhere in the Android Docs since the ubiquitous use of `Fragments` ...

**Comment by tmmiller1982** [comment]
ah very nice.  Good find!

**Comment by quangtrung89** [comment]
Can you please show me the code how you change from FragmentPagerAdapter into FragmentStatePagerAdapter?

**Comment by AeroEchelon** [comment]
You can populate this `ViewPager` with `FragmentStatePagerAdapter` provided by the SDK [here](http://developer.android.com/reference/android/support/v4/app/FragmentStatePagerAdapter.html).

**Comment by ttgdz** [comment]
I'm seeing this issue too,but I use view instead of fragment,and sometimes the page is blank...Any suggestions?

**Comment by kasumbarobert** [comment]
Did anyone get a solution to this?

**Comment by asadmukhtar28** [comment]
Kindly Help me guys, i have a simple image silder implementation with Viewpager and using PagerAdapter my VIewpager show sometimes empty.

**Comment by kevinjmz** [comment]
Hello guys. I was having the same problem, then I noticed that I was creating multiple instances of my adapter, since it was being created and instantiated on OnViewCreated. To fix this I created a PagerAdapter global variable, then I instantiate the variable **ONLY** within OnCreateView. This fixed my issue of going back and creating new empty screens.

**Comment by dbof10** [comment]
I'm having the same issue. it's more like google viewpager than this viewpager.
