### ISSUE TITLE
Gradle-like usage

### ISSUE THREAD

**Issue by radimvaculik** [antonyt/InfiniteViewPager#24]
Hi! It should be great to public this awesome library somewhere to use it with gradle!

**Comment by jitpack-io** [comment]
Well now you can https://jitpack.io/#antonyt/InfiniteViewPager/1cda8c0c80 :)
See the steps in the link on how to add InfiniteViewPager as a dependency in Gradle.

**Comment by radimvaculik** [comment]
Thanks!
